FROM 192.168.2.192/microservice/openjdk:7-jre
MAINTAINER xxx xxx@imooc.com

COPY ./course-edge-service-1.0-SNAPSHOT.jar /course-edge-service.jar

ENTRYPOINT ["java", "-jar", "/course-edge-service.jar"]