version: "3.4"
services:
  message-service:
    image: 192.168.2.192/microservice/message-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"

  user-service:
    image: 192.168.2.192/microservice/user-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"

  user-edge-service:
    image: 192.168.2.192/microservice/user-edge-service:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8082:8082"
    placement:
            constraints: [node.role == manager]
#            constraints: [node.role == worker]
    healthcheck:
#      test: ["CMD", "curl", "-f", "http://www.mooc.com/user/login"]
      test: ["CMD", "curl", "-f", "http://localhost:8082/user/login"]
      interval: 60s
      retries: 3
      timeout: 10s
    depends_on:
      - user-service
      - message-service

  course-service:
    image: 192.168.2.192/microservice/course-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    depends_on:
      - user-service

  course-edge-service:
    image: 192.168.2.192/microservice/course-edge-service:latest
    deploy:
      endpoint_mode: vip
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8081:8081"
    depends_on:
      - user-edge-service
  api-gateway:
    image: 192.168.2.192/microservice/api-gateway-zuul:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8080:80"
    depends_on:
      - user-edge-service
      - course-edge-service

networks:
  default:
    external:
      name: imooc-overlay